#ifndef __KSU_UAPI_SELINUX_H
#define __KSU_UAPI_SELINUX_H

#include <linux/types.h>

#define DEFINE_KSU_UAPI_CONST(type, name, val) \
    enum { name = (val) }; \
    static const type name##_RUST = (val);

DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_NORMAL_PERM, 1)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_XPERM, 2)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_TYPE_STATE, 3)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_TYPE, 4)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_TYPE_ATTR, 5)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_ATTR, 6)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_TYPE_TRANSITION, 7)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_TYPE_CHANGE, 8)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_CMD_GENFSCON, 9)

DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_NORMAL_PERM_ALLOW, 1)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DENY, 2)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_NORMAL_PERM_AUDITALLOW, 3)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DONTAUDIT, 4)

DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_XPERM_ALLOW, 1)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_XPERM_AUDITALLOW, 2)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_XPERM_DONTAUDIT, 3)

DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_TYPE_STATE_PERMISSIVE, 1)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_TYPE_STATE_ENFORCE, 2)

DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_CHANGE, 1)
DEFINE_KSU_UAPI_CONST(__u32, KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_MEMBER, 2)

#undef DEFINE_KSU_UAPI_CONST

#endif